sudo: false
dist: trusty
language: python
python:
    - "2.7.13"
    - "3.6.0"
#   - "nightly"  # currently points to 3.7-dev
# command to install dependencies
before_install:
    - git clone --depth=50 --branch=master https://github.com/openwhisk/openwhisk.git ~/openwhisk
install:
    # - pip install .
    - pip install -r requirements.txt
    - pip install flake8
# preflight
before_script:
    flake8 ~/openwhisk --count --max-line-length=127 --statistics --exit-zero
# command to run tests
# script: nosetests
script:
    - ls
    - chmod +x *.py
    # - ./get_wsk_auth.py  # would do a webserver.open()
    - ./hello.py           # make sure example is still valid
    # - ./openwhisk.py     # self test will fail without a wsk_auth
    - python test_data_types.py
    - python test_logger.py
    - python test_url_generator.py
notifications:
    on_success: change
    on_failure: always
